name: audio_codec
description: A library to decode and perhaps encode audios
version: 0.0.1
homepage: https://clementbeal.github.io/
repository: https://github.com/ClementBeal/audio_codec
issue_tracker: https://github.com/ClementBeal/audio_codec/issues

topics:
  - audio
  - codec
  - decoder
  - encoder

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  convert: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
