import 'dart:io';

void main(List<String> args) {
  var polynomial = 0x8005;
  var constName = 'crc16';
  String? outPath;

  for (int i = 0; i < args.length; i++) {
    final arg = args[i];
    switch (arg) {
      case '--polynomial':
      case '-p':
        if (i + 1 >= args.length) {
          _fail('Missing value for $arg');
        }
        polynomial = _parseInt(args[++i]);
        break;
      case '--const-name':
      case '-n':
        if (i + 1 >= args.length) {
          _fail('Missing value for $arg');
        }
        constName = args[++i];
        break;
      case '--out':
      case '-o':
        if (i + 1 >= args.length) {
          _fail('Missing value for $arg');
        }
        outPath = args[++i];
        break;
      case '--help':
      case '-h':
        _printUsage();
        return;
      default:
        _fail('Unknown argument: $arg');
    }
  }

  final table = _buildCrc16Table(polynomial);
  final output = _formatDartTable(
    constName: constName,
    polynomial: polynomial,
    values: table,
  );

  if (outPath == null) {
    stdout.write(output);
    return;
  }

  final file = File(outPath);
  file.writeAsStringSync(output);
  stdout.writeln('Wrote ${table.length} entries to ${file.path}');
}

List<int> _buildCrc16Table(int polynomial) {
  final table = List<int>.filled(256, 0, growable: false);

  for (int i = 0; i < 256; i++) {
    int crc = i << 8;
    for (int bit = 0; bit < 8; bit++) {
      if ((crc & 0x8000) != 0) {
        crc = ((crc << 1) ^ polynomial) & 0xFFFF;
      } else {
        crc = (crc << 1) & 0xFFFF;
      }
    }
    table[i] = crc;
  }

  return table;
}

String _formatDartTable({
  required String constName,
  required int polynomial,
  required List<int> values,
}) {
  final buffer = StringBuffer();
  buffer.writeln('// Generated by tool/generate_crc16_table.dart');
  buffer.writeln('// Polynomial: ${_hex(polynomial, width: 4)}');
  buffer.writeln('// dart format off');
  buffer.writeln('const $constName = [');

  const entriesPerLine = 8;
  for (int i = 0; i < values.length; i += entriesPerLine) {
    final lineEnd = (i + entriesPerLine < values.length)
        ? i + entriesPerLine
        : values.length;
    final row = values
        .sublist(i, lineEnd)
        .map((value) => _hex(value, width: 4))
        .join(', ');
    buffer.writeln('  $row,');
  }

  buffer.writeln('];');
  buffer.writeln('// dart format on');
  buffer.writeln('');
  buffer.writeln(
      '/// Computes CRC-16 (MSB-first) using the generated lookup table.');
  buffer.writeln('int calculateCRC16(List<int> bytes) {');
  buffer.writeln('  int crc = 0;');
  buffer.writeln('');
  buffer.writeln('  for (final byte in bytes) {');
  buffer.writeln('    final tableIndex = ((crc >> 8) ^ byte) & 0xFF;');
  buffer.writeln('    crc = ((crc << 8) ^ $constName[tableIndex]) & 0xFFFF;');
  buffer.writeln('  }');
  buffer.writeln('');
  buffer.writeln('  return crc;');
  buffer.writeln('}');
  return buffer.toString();
}

String _hex(int value, {required int width}) {
  return '0x${value.toRadixString(16).padLeft(width, '0')}';
}

int _parseInt(String value) {
  final parsed = int.tryParse(value);
  if (parsed != null) {
    return parsed;
  }

  final normalized =
      value.toLowerCase().startsWith('0x') ? value.substring(2) : value;
  final hexParsed = int.tryParse(normalized, radix: 16);
  if (hexParsed != null) {
    return hexParsed;
  }

  _fail('Unable to parse integer: $value');
}

Never _fail(String message) {
  stderr.writeln('Error: $message');
  _printUsage();
  exitCode = 64;
  throw StateError(message);
}

void _printUsage() {
  stdout.writeln('Usage: dart run tool/generate_crc16_table.dart [options]');
  stdout.writeln('');
  stdout.writeln('Options:');
  stdout.writeln(
      '  -p, --polynomial <int>  CRC polynomial (default: 0x8005, accepts 0x...)');
  stdout.writeln(
      '  -n, --const-name <name> Const name in output (default: crc16)');
  stdout
      .writeln('  -o, --out <path>        Output file path (default: stdout)');
  stdout.writeln('  -h, --help              Show this help');
}
